# src/UserBundle/Resources/config/validation.yml
Userbundle\Entity\User:
    properties:
        email:
            - Email:
                message: The email "{{ value }}" is not a valid email.
                checkMX: true