<?php

namespace PostIt\AnnounceBundle\Repository;

/**
 * AnnounceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnnounceRepository extends \Doctrine\ORM\EntityRepository
{
	public function getAll()
	{
		$qb = $this->createQueryBuilder('a')
		->addOrderBy('a.date', 'DESC');
        $qb->setMaxResults(10);
    return $qb->getQuery()->getResult();
	}
}
